services:
  backend:
    build: ./backend
    container_name: chess_backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: chess_frontend
    ports:
      - "4321:4321"
    depends_on:
      - backend
